##============================================================================= 
##                                   全局变量                                ##
##=============================================================================
ssh_user: admin                ## SSH 远程用户, 一般禁用root, 通过sudo或者su方式
rke2_version: v1.36.3+rke2r1   ## 指定RKE2 Kubernetes安装包、离线资源部署版本
arch: amd64                    ## 服务器CPU硬件架构 amd64=x86_64、arm64=aarch64 用于区分对应架构二进制、镜像包
download_proxy: "https://gh-proxy.com/ https://ghfast.top/ https://ghproxy.net/"  ##  GitHub 加速: 空格分隔多个, 依次尝试直至成功, 留空则直连
global:
  install_source: "online"
  ansible_dir: "{{ playbook_dir }}/.."
  docker_repo:
    host: "harbor.kubecy.com"  ## 私有镜像仓库
    host_ip: "192.168.1.150"   ## 镜像仓库 IP (内网域名需写入 /etc/hosts 时配置, 留空跳过)
    user: "admin"
    password: "Harbor123@!"
    disable_default_registry_endpoint: true
  k8s_user:                    ## 管理 K8S 集群专用用户                            
    group: kubeadmin
    gid: 2456
    user: kubeadmin
    uid: 2456
    password: kubeadmin123@!
  token: "RtMjcuJSVrbVlTBwQwisumREZWtMgH6RiKOXSsMKwAJsvGRaxaMIPOE+U6GKySQj"
  profile: ""                                                  ## 基准测试验证系统配置: cis 根据实际情况配置
  pkg_rke2: "packages_rke2"
  software_dir: /app/rke2                                      ## RKE2 二进制包目录
  rke2_worker_dir: /etc/rancher/rke2                           ## RKE2工作目录 
  rke2_data_dir: /var/lib/rancher/rke2                         ## 官方推荐不要改变, RKE2数据目录: IO 极敏感的场景下把 /var/lib/rancher/rke2/server/db（etcd）单独挂一块高性能磁盘
  etcd_data_dir: /var/lib/rancher/rke2/server/db/etcd          ## 存储Kubernetes集群状态（Pods, Services, Secrets等）
  containerd_data_dir: /var/lib/rancher/rke2/agent/containerd  ## 存储容器镜像
  kubelet_dir: /var/lib/kubelet                                ## 用于管理 kubelet 文件的根目录（Pod 卷、emptyDir、插件 socket等）  
  partition:                                                   ## rke2-server、rke2-agent主机磁盘分区
    enabled: false                                             ## 分区开关: true Or false
    etcd_dir_disk: "sdb"                                       ## 如果none，则etcd目录不单独挂载。
    containerd_data_dir_disk: "sdc"                            ## rke2_data_dir 挂载盘 (nvme0n2 或 sdb, 按用户环境定义)
    kubelet_dir_disk: "sdd"                                    ## kubelet_dir 挂载盘 (nvme0n3 或 sdc, 按用户环境定义)
    format_type: "xfs"                                         ## 分区文件系统类型 (xfs/ext4)

  ha_ip: "192.168.1.110"

##============================================================================= 
##                                K8S MASTER                                 ##
##============================================================================= 
rke2_server:
  kube_vip:
    enabled: true                              ## kube-vip开关: true Or false
    kube_vip_version: "v1.2.3"                 ## 镜像版本 KVVERSION=$(curl -sL https://api.github.com/repos/kube-vip/kube-vip/releases | jq -r ".[0].name")
    kube_vip_interface: "ens33"                ## 接口
    virtual_ip: "{{ global.ha_ip }}"           ## Kube-VIP

  db:
    user: etcd
    uid: 2011
    group: etcd
    gid: 2011
    etcd_expose_metrics: true                       ## 暴露 etcd 指标
    etcd_disable_snapshots: false                   ## 禁用 etcd 自动快照
    etcd_snapshot_schedule_cron: "0 */8 * * *"      ## 快照间隔时间 
    etcd_snapshot_retention: 12                     ## 要保留的快照数量
    etcd_snapshot_compress: true                    ## 压缩 etcd 快照

  cni: "cilium"                           ## 部署的 CNI 插件, 可选值: none, calico, canal, cilium, multus 作为第一个值以启用 multus 元插件
  cluster_cidr: "10.244.0.0/16"           ## Pod IP 的 IPv4/IPv6 网络 CIDR
  service_cidr: "10.96.0.0/16"            ## 服务 IP 的 IPv4/IPv6 网络 CIDR 
  cluster_dns: "10.96.0.10"               ## CoreDNS 服务的 IPv4 集群 IP 地址, 在服务 CIDR 范围内
  service_node_port_range: "30000-65000"  ## NodePort 可见性的服务预留端口范围
  cluster_domain: "cluster.local"         ## Kubernetes 集群的 DNS 域后缀配置项

  tls_san:
    - "{{ global.ha_ip }}"     ## HA_VIP, 必须在第一行
    - "rke2-vip.kubecy.com"    ## 配置域名
    - 192.168.1.61             ## RKE2 SERVER1
    - 192.168.1.62             ## RKE2 SERVER2
    - 192.168.1.63             ## RKE2 SERVER3

  node_taint:                  ## MASTER 注册带有污点 
    - "node-role.kubernetes.io/control-plane=true:NoSchedule"

  disable_cloud_controller: true            ## 禁用 rke2 默认云控制器管理器

  ingress_controller: "none"                ## 部署的 Ingress Controller, 默认：traefik, 另外参数: none, ingress-nginx

  cilium:                                   ## HelmChartConfig 配置 Cilium 清单
    disable_kube_proxy: true                ## 是否禁用 kube-proxy, 默认是：false; 如果需要禁用则修改为：true
    kubeproxyreplacement: true              ## 完全替代 kube‑proxy, 使用KPR模式
    
    ipam:                                   ## 配置IP地址管理模式
      mode: "kubernetes"                    ## cluster-pool: cilium‑operator管理；单一大 IP 池，网段存于CiliumNode; kubernetes: 网段写入原生Node.spec.podCIDR；cilium 仅在已分配网段内分发 IP
      ciliumNodeUpdateRate: "15s"           ## 更新 CiliumNode 自定义资源的最大刷新速率
      operator:
        clusterPoolIPv4PodCIDRList: ["10.118.0.0/16"]  ## IPv4 Pod总地址池：集群所有Pod IPv4网段资源池
        clusterPoolIPv4MaskSize: 24                    ## 单节点IPv4子网掩码：每节点分配/24网段，单节点可用254个Pod IP，通用规格
        clusterPoolIPv6PodCIDRList: ["fd00::/104"]     ## IPv6 Pod总地址池
        clusterPoolIPv6MaskSize: 120                   ## 单节点IPv6子网掩码：每节点分配/120网段，单节点可用254个IPv6 Pod IP，与IPv4容量对齐

    ingressController:                      ## ingressController 参数配置
      enabled: false                        ## 开启 cilium ingress controller, 前提条件: 必须 kubeProxyReplacement=true 和 l7Proxy=true (默认启用,L7 代理)
      loadbalancerMode: "dedicated"         ## 支持参数: shared, dedicated
      hostNetwork:
        enabled: true                       ## 支持参数: true, false; 启用 Cilium 入口控制器主机网络模式, 在负载均衡器服务不可用的情况下非常有用，例如拥有集群外部负载均衡器的环境中(Cilium 1.16+起支持)
        sharedListenerPort: 8080            ## HTTP, HTTPS 共用
        httpPort: 0                         ## cilium 1.20+ 开始支持, 可单独设置 HTTP 监听端口, 如果未设置或为0，则使用sharedListenerPort。
        httpsPort: 0                        ## 同上
        tlsPassthroughPort: 0               ## 同上
   
    gatewayAPI:                            ## 启用 Cilium 对网关 API 的支持
      enabled: true
      hostNetwork:                         ## 配置Envoy侦听器是否应在主机网络上公开
        enabled: false
    loadBalancer:                           ## 配置服务负载平衡
      algorithm: "random"                   ## random or maglev
      mode: "dsr"                           ## 后端负载均衡的操作模式。e.g. snat, dsr, hybrid

    socketLB:                               ## 配置 socket LB
      enabled: true
      hostNamespaceOnly: false
      terminatePodConnections: true
      tracing: true

    ipv4:
      enabled: true                         ## 启用 IPv4 支持, 默认开启
    ipv6:
      enabled: true                         ## 启用 IPv6 支持, 默认开启

    gatewayAPI:
      enabled: true                         ## Enable support for Gateway API in cilium

    bpf:
      masquerade: true
      hostLegacyRouting: false

  disable:                                  ## 禁止部署已打包的组件, 有效项: rke2-coredns, rke2-ingress-nginx, rke2-metrics-server
    - rke2-ingress-nginx
    - rke2-metrics-server 

  write_kubeconfig: /etc/rancher/rke2/rke2.yaml
  write_kubeconfig_mode: "0644"
  
  control_plane_resource_requests:   ## 控制平面资源请求, 根据实际集群规模配置, 
    - kube-apiserver-cpu=500m
    - kube-apiserver-memory=1024M
    - etcd-cpu=1000m
    - etcd-memory=1024M
    - kube-controller-manager-cpu=200m
    - kube-controller-manager-memory=512M
    - kube-scheduler-cpu=200m
    - kube-scheduler-memory=512M
    - kube-proxy-cpu=500m
    - kube-proxy-memory=512Mi
  control_plane_resource_limits:     ## 控制平面资源上限
    - kube-apiserver-cpu=2000m
    - kube-apiserver-memory=4Gi
    - etcd-cpu=2000m
    - etcd-memory=4Gi
    - kube-controller-manager-cpu=1000m
    - kube-controller-manager-memory=2Gi
    - kube-scheduler-cpu=500m
    - kube-scheduler-memory=1Gi
    - kube-proxy-cpu=500m
    - kube-proxy-memory=512Mi

## kubernetes 控制平面组件参数配置项
  kube_apiserver_arg:
    - max-requests-inflight=600
    - event-ttl=12h
  etcd_arg:
    - data-dir={{ etcd_data_dir }}
    - auto-compaction-retention=8h
    - quota-backend-bytes=8589934592
    - heartbeat-interval=200

  kubelet_arg:
    - root-dir={{ global.kubelet_dir }}
    - max-pods=120

  kube_proxy_arg:                             
    - proxy-mode=nftables                        ## 代理模式参数:  'iptables'（默认）, 'ipvs' 或 'nftables'
    - ipvs-strict-arp=true                       ## 用 MetalLB 时, 需要配置

##============================================================================= 
##                                K8S WORKER                                 ##
##============================================================================= 
rke2_agent:
  kubelet_arg:
    - root-dir={{ global.kubelet_dir }}
    - max-pods=120

  kube_proxy_arg:
    - proxy-mode=nftables                        ## 代理模式参数:  'iptables'（默认）, 'ipvs' 或 'nftables'
    - ipvs-strict-arp=true                       ## 使用 MetalLB 时, 需要配置
